### PR TITLE
BBS section

### LINKED ISSUE #48: BBSs as database entries
I think it would be a good idea to enhance our database by including boards as entries. Boards have always been an important part of the different scenes up to the second half of the 1990s, many demosceners have been (co-)sysops, most demogroups had BBS affils, many coded BBS intros etc.

I have been setting up a BBS database within pouet some five-six years ago when PS was so kind to code the infrastructure for it: http://www.pouet.net/boards.php -- however, with Demozoo this could become much more amazing.

I propose the following content categories for within a BBS entry:

NAME: BBS Name (alternative names, as with groups, should be allowed since some boards renamed themselves over time)

LOCATION: Use the same location engine as with individual sceners. I am very much against having a field with telephone numbers, because even if a board was 100% leagl, this still could be unpleasant for the former sysop (or annoying for the poor people who own the number now).

STAFF: This could be done in the manner of prod credits, but with following pulldown roles "Sysop", "Co-Sysop". 

AFFILS: Also like prod credits, but with groups, not sceners, to enter. Following pulldown roles: "WHQ", "HQ", "Memberboard", "Distsite"

BBS INTROS: Possibility to link prods, like invitros are linked to parties.

TEXT ADS: Possibility to upload textmode BBS ads and probably display them with Ansilove.

This is just a suggestion, of course, and I am no coder, but this is not that hard to achieve, is it? And the value to scene history preservation would be immense.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #48. I've taken the liberty of merging productions / music / graphics into one section to make space for the new menu item - I await your pitchforks and torches. :-)

Currently implemented: location, notes, BBStros, staff, group affiliations; backlinks from group, scener, prod pages
Not yet implemented: alternative names, ex-staff, adding BBS links from the other direction (i.e. from the group / scener / prod page), importing data from Pouet

### CODE REVIEW

**Comment by gasman** [comment]
Also just remembered another thing not yet implemented: search.

**Comment by gasman** [comment]
Feedback from @dipswitch-:
- add location flags to staff listing (apparently it doesn't just duplicate the board location...)
- make the group affiliation status optional

**Comment by glennlunder** [comment]
The "importing data from Pouët" bit was opposed by Gargaj in the original issue, if you read down it.

We do have a lot of data from the Janeway data dump that we could mine, though.

**Comment by gasman** [comment]
I think Gargaj was more opposed to the duplication of work, which is exactly what a data import would avoid :-)

And in a spot of excellent timing, he's [working on adding BBSes to the API](https://www.pouet.net/topic.php?post=567529) right now...

**Comment by sagamusix** [comment]
I think the all-caps "BBSES" in the header looks strange. could we maybe use text-transform: small-caps for that one button so that it looks like "BBSᴇs"?

**Pull request merged**
