### PR TITLE
upgraded Demozoo to Django 1.9

### PR DESCRIPTION
**Pull request by jensadne**
As the subject says things have been updated to work with Django 1.9.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @jensadne - any thoughts on how we perform the db migration step when rolling out the upgrade? Normally I'd expect to do `./manage.py migrate --fake`, but it looks like that won't work when upgrading directly from 1.6 to 1.9 because there's a legitimate change to the `django_content_types` table which gets missed if you fake the migrations; and `./manage.py migrate` also fails (because it tries to create the `django_content_types` table which already exists).

I suspect the answer will be to do 1.6 -> 1.7 as a separate step, i.e. run `./manage.py migrate --fake` with Django 1.7 installed. This in turn would require us to create a separate branch that restores enough Django 1.7 compatibility to let the migrations run - currently it fails with a django-debug-toolbar error. Does that sound like the way to go?

**Comment by jensadne** [comment]
@gasman just doing ./manage.py migrate --fake-initial worked fine here, then the migrations we actually need from contenttypes and auth are applied properly.

**Comment by gasman** [comment]
@jensadne What's the status of Djapian now? Currently `manage.py index` is failing for me with the error: `django.db.transaction.TransactionManagementError: This is forbidden when an 'atomic' block is active.`

**Comment by jensadne** [comment]
Hmm. I have to check that when I get home, but I did have Djapian working when I worked on this at Datastorm.

**Comment by gasman** [comment]
A little status update... I'm working on getting the staging site set up on a separate zetta.io VM as an exact replica of the live site, including all peripheral bits that we may have previously skipped on staging, namely: search indexing, background tasks for screenshots and scene.org spidering, SceneID, zxdemo.org and HTTPS. This should help us in two respects:

* it means we can set people loose testing _everything_ on staging, rather than having grey areas where we can't distinguish between things that are genuinely broken and things that just haven't been set up on staging
* it avoids any nasty surprises if (e.g.) running under HTTPS has unforeseen quirks in Django 1.9

Right now I need to do a bit of refactoring of how we handle image uploads for homepage banners, news stories and platform pictures: we need to store the full URL for these images, rather than just the S3 bucket path, so that the staging site can have a mixture of the existing images from the live site (hosted at media.demozoo.org) and images uploaded on staging (hosted at staging-media.demozoo.org). That in turn will require a (South) database migration, which then needs to be reflected in the 'initial' Django migrations. No big deal, just a bit of extra faff :-)

**Comment by gasman** [comment]
The staging site at https://staging.demozoo.org/ (access details: demozoo / demozoo) is now running the Django 1.9 branch for testing. Assuming no major issues come up, I'll switch the live site over on Monday next week (29th May).

**Comment by glennlunder** [comment]
Issue found: Can not delete links from productions, groups nor individual sceners. No error message or any indicator as to why, whenever I remove a link, I just return to the page with the link still there. Logged in as myself through Scene ID, so I should in theory have privileges to delete shit - though I guess I should get an error message if that was the issue?

**Comment by glennlunder** [comment]
Also applies to links I myself have created on staging - I can not delete those either, so all links are equal in this sense.

**Comment by jensadne** [comment]
Took a quick look at the handling of external links now and it does sound familiar from an issue I've had earlier with deleting things in formsets, iirc something changed with that feature in either 1.7 or 1.8 which I think would have this exact effect. I can take a look at it tonight if @gasman doesn't get there first. ;-)

**Pull request merged**
