### PR TITLE
fixed issue in ticket

### PR DESCRIPTION
**Pull request by nswaldman**
…but really, everything about spawning_formset functionality is hairier than what lurks beneath nosfe's kilt. 

One door closes, another opens. Lather, rinse, repeat. You get the point.

### CODE REVIEW

**Comment by gasman** [comment]
Could we have this without the tab->space conversion, please? :-)

**Comment by nswaldman** [comment]
If it helps close this ticket, sure.

However: CSS and its pre-processing ilk tend to be formatted with two spaces rather than a legit tab. Recent IDEs and code conventions pretty much make it the (enforceable) norm -and I agree.

If Demozoo must be all-tabs, it would be a good thing to look into a code prettifier to enforce that convention?

**Comment by gasman** [comment]
Afraid I'm getting some glitchy animation on both Chrome and Firefox (on OS X) here: when adding a row, it expands to what looks like twice the correct height before snapping back into place.

**Comment by nswaldman** [comment]
I needed a veritable time machine for that one: slideDown in jQuery apparently can (and will) yield unexpected glitchiness without explicitly set widths. I don't know if more recent builds will fix that behaviour, but for now let's disable the animation in favour of things being functional and not broken-looking.

**Comment by gasman** [comment]
Fair enough :-) Merged in 2a4a5409c0b1e4ac22e0cde6baab36bdeb66a27c (+ parent) now - cheers!

**Pull request closed without merging**
