### PR TITLE
Feature: Livecode demozoo as groklink for party link

### PR DESCRIPTION
**Pull request by totetmatt**
Context : https://github.com/demozoo/demozoo/issues/567 

Adding Livecode as groklink so it appears with logo and label 'Livecode' .

Learnig codebase, so I might have miss some point.

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @totetmatt!

Given that a livecode link points to a party _series_ rather than an individual party edition, and there's an increasingly urgent need to support arbitrary links at the party series level (#566), I think it might make sense to hold off on this until I've implemented that - otherwise I'll end up having to reshuffle the data, deal with duplicates and so on when that change happens.

**Comment by totetmatt** [comment]
Hey Gasman thanks for the heads up.
Ok I see, we sure can hold off. I thought it could have been an easy fix just to ease the visibility and link between DZ and LCDZ.

> Given that a livecode link points to a party series rather than an individual party edition

Livecode do actually have the difference between the 2 : 
One particular event : https://livecode.demozoo.org/event/2023_04_08_shader_showdown_revision.html
One Serie : https://livecode.demozoo.org/serie/Revision.html
 (tl;dr behind the scene (pun) it's based on demozoo  [serie] <-> [party] data model) 

It's even more complex actually as an event isn't automatically representing only one "Edition" e.g for Revision 2023 we have : 
* Showdown : https://livecode.demozoo.org/event/2023_04_08_shader_showdown_revision.html
* Jam : https://livecode.demozoo.org/event/2023_04_08_shader_jam_revision.html

**Comment by totetmatt** [comment]
Just for Information, I added an extra tag per event in the html header : 

meta name="lcdz_json" content="<json_url>"

So if there is a link to an event, it's possible to have extra processing based on structured data

**Comment by gasman** [comment]
Merged in 37640ad1fefbb66dcba7a063f8f0174a242e41cf, with tweak in 162b6ec8c72bec45a6d645f727d65f4dd59361a0 so that we're linking by party series rather than individual party. As you point out, LCDZ's concept of an "event" doesn't map nicely to parties right now, but it will do when we complete #484 (which is pretty close now)!

**Pull request closed without merging**
