### PR TITLE
fixes #239 updated instructions in Readme.md

### LINKED ISSUE #239: update readme.md
I had a couple of issues getting demozoo up and running locally. I'll update the readme.md to identify the issues I had and make it easier for first timers.

### PR DESCRIPTION
**Pull request by DannyCork**
fixes #239

### CODE REVIEW

**Comment by nswaldman** [comment]
I can see how a terse description of the commands would help a first-time installation, but it seems a bit much to add copious terminal output to the documentation. What kind of issue did you run into that could be helped by that?

**Comment by DannyCork** [comment]
Hey Nuey,
I was unable to run the server using:
 ```./manage.py runserver 0.0.0.0:8000```

 Instead I had to google and eventually got it working using
 ```python ./manage.py runserver 0.0.0.0:8000```

My commit doesn't include copious terminal output but rather better explains the commands needed and the expected output.The objective here is to make it as simple as possible for first time users to contribute to DemoZoo. Making the instructions more user friendly can only benefit this objective.

**Comment by nswaldman** [comment]
The terminal output examples are in no way helpful to resolve your problem and given solution. The concept that "if it looks like this, it's golden" is a bad example to set. When a user encounters a problem, he'll have to google and/or ask the demozoo people anyway. All it really does is tell people when the documentation was last updated (dates, version numbers, etc). That's not in the spirit of keeping things simple.

Other than that, you might want to test whether invoking the python interpreter explicitly is a reproducible problem. As easy as it is to wreck a Vagrant box for demozoo, I can't reproduce that issue (and yes, I re-did my vagrant setup several times today for the fun of it).

**Comment by DannyCork** [comment]
Hey Nuey,
Let's put this in perspective.My commit updates a couple of lines of documentation, that's all.. 

It's not a significant change and in my opinion It shouldn't warrant such an intense reaction. I find your over the top reaction as a disincentive to contributing to DemoZoo. Maybe that wasn't your intention but that's the vibe I get.

I'll shutup now, no point in getting dragged into an argument over  a couple of lines in a readme.md.

**Comment by gasman** [comment]
> Other than that, you might want to test whether invoking the python interpreter explicitly is a reproducible problem.

It's a result of running on a Windows host machine, I think - the manage.py script won't have the executable bit set. (It _might_ be possible to fix that in the install script, but I don't know enough about Vagrant shared folders to say for sure...)

**Comment by DannyCork** [comment]
yes I encountered this issue using a Windows host. 
I'll close this pr , and open a separate one with just the info about the alternative way to run manage.py

**Pull request closed without merging**
