### PR TITLE
Retrotxt v1.0

### PR DESCRIPTION
**Pull request by bengarrett**
This is a custom client-side viewer for CP-437, Windows-1252, and Amiga ISO-8859-1 text. It applies text transformations and styling to the text content of an element with the `retrotxtCanvas` id.

The JS uses modern features such as ES6, classes, and modules. The initializer `retrotxt-init.js` is in legacy JS and runs browser feature tests. If any fail, the script exits gracefully. If there is no `retrotxtCanvas` element on the page it also exits before loading any heavy fonts, css, or other JS.

rt_for_dz

---

You may wish to modify the `base.html` template to only display the 

```html
<script src="{% static 'retrotxt/js/retrotxt-init.js' %}">
``` 

element when the `show_text_ad`, `results_file` and `show_info_files` templates are in use?

---

Defaults can be selected via the templates using a class style on the `retrotxtCanvas` element. 

An example is used by the `show_text_ad.html` which has the class `retrotxt-msdos` to select MS-DOS onload.

```html
<pre id="retrotxtCanvas" class="retrotxt-msdos">{{ text_ad.text }}</pre>
```

If no class is provided, Unicode (the default DZ text display) will be used.

Class values for default selections: `retrotxt-msdos` MS-DOS; `retrotxt-amiga` Amiga; `retrotxt-windows` Windows.

I think for sane defaults, any text file for an Amiga or MS-DOS production should use their respected viewer?

Eventually, maintainers would want to select a default view per text file, which I imagine could be done like so?

```html
<pre id="retrotxtCanvas" class="{{ text_ad.view }}">{{ text_ad.text }}</pre>
```

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @bengarrett - this is looking really good from an initial test!

Do you have a non-minified version of the code? We're using django-compressor elsewhere to strip whitespace, and it would be good to do the same thing here - that way we've got an easily editable version of the code as part of the repo, in case we need to do any maintenance on it in future. That will also allow setting things up so that it's only included on the views that use it.

**Comment by bengarrett** [comment]
> Thanks @bengarrett - this is looking really good from an initial test!
> 
> Do you have a non-minified version of the code? We're using django-compressor elsewhere to strip whitespace, and it would be good to do the same thing here - that way we've got an easily editable version of the code as part of the repo, in case we need to do any maintenance on it in future. That will also allow setting things up so that it's only included on the views that use it.

Hi, great! I plan to have the source code in its own GH repo when I have written up the documentation done etc. I will link to it here when it is online.

**Comment by bengarrett** [comment]
Hi, there is now a public repo at https://github.com/bengarrett/retrotxtjs and an npm package at https://www.npmjs.com/package/retrotxt.

There's a bug fix in the repo for CP-437 reencoding that's not in this pull request.

**Comment by gasman** [comment]
Sorry for the delay in reviewing...
Now that I've been able to look into the code and documentation, it seems that the package as a whole is aimed at fixing a problem that Demozoo doesn't actually have - namely, re-encoding text that's consistently being served in the wrong encoding. When a file is known to be in CP437, such as https://demozoo.org/parties/707/results_file/153/, we already serve it correctly, which means that the Retrotxt conversion ends up stripping out the block graphics. On the other hand, we have files like https://demozoo.org/parties/293/results_file/1255/ which are in a different encoding entirely, and judging from https://int10h.org/oldschool-pc-fonts/readme/#plus_charset VileR's fonts would be able to display them fine if we just applied those fonts with no character conversion.

The font selector is definitely worth keeping, so I think the way forward here is to implement that without the character conversion step, and also to enable our [interface for manually fixing encodings](https://github.com/demozoo/demozoo/commit/748c3e0e8bba0a04b27a57fdb6e787532ff2ef4f#diff-b1b2af8d23223fb3931096c48199d8e9143e63cc7efe71a68692077002be2f2f) on things that don't currently have it - right now I think we only have that for results files, not nfo files for prods and BBSes.

**Comment by gasman** [comment]
Now implemented via #499 and #500. Thanks for leading the way!

**Pull request closed without merging**
