### PR TITLE
#293 UX: Added line break before party url.

### PR DESCRIPTION
**Pull request by DannyCork**
Addresses #293

Tested on Chrome (Windows) & Safari (Mac) , screenshots:

Screenshot 2019-03-27 at 00 41 45
Screenshot 2019-03-27 at 00 42 10

-----

Tested on mobile:

Screenshot 2019-03-27 at 00 43 07

for @sagamusix  :)
pr for review @nswaldman @gasman @emoon @glennlunder

### CODE REVIEW

**Comment by DannyCork** [comment]
would be nice to get this reviewed :) @nswaldman @gasman @emoon @glennlunder  @sagamusix :) @Bombe

**Comment by glennlunder** [comment]
@DannyCork Those that admin the code (I myself am not a dev) will look at when they find the time. We all get notified of it, so no need to nudge. We didn't forget, we've just not gotten there yet.

Patience, young padawan. :)

**Comment by DannyCork** [comment]
It's now July and this is sitting in review since the end of March. The pr is a couple of characters, not rocket sciene.

This isn't exactly encouraging people to contribute to DemoZoo.

**Comment by Bombe** [comment]
Using <br> for formatting sounds like a horrible idea. Better solution would be to adjust the CSS, I guess… then again, I have never even seen the code so I’m not sure why I was tagged here.

**Comment by gasman** [comment]
Sorry for the delay in looking at this...

I don't mind the use of `<br>` too much here - anyone who feels particularly strongly about a neater more semantic solution is more than welcome to submit a PR themselves :-)

However, as it stands this is malformed HTML - you have content inside a `<ul>` that isn't inside a `<li>` - which is going to be bad for maintainability.

**Comment by gasman** [comment]
Fixed in 30ed5acad7bdd562628d418b759f5827b2ea096f. Thanks for looking into this, @DannyCork!

**Pull request closed without merging**
